#!/bin/bash
O=$1
i=$2
BACKOFF=-witten_bell
MEMSIZE=64M
POINTCUT=4
[ "$i" = "0" ] || ii=${O}.arpa.$(($2-1))
time gzip -d < ${O}.scz.gz |
	./sc-train \
		--wordlist ${O}.vocab \
		--replay $ii \
		2>${O}.log.sc-train.$i |
	LANG=C grep -v -F '<' |
	gzip > ${O}.sc$i.gz

time gzip -d < ${O}.sc$i.gz |
	LANG=C sort \
		-S$MEMSIZE \
		-T $(dirname $O)|
	./sc2wngram $POINTCUT |
	gzip > ${O}.wngram.$i.gz

time gzip -d < ${O}.wngram.$i.gz|
	../../CMU-Cam_Toolkit_v2/src/wngram2idngram \
		-n 2 \
		-temp $(dirname $O) \
		-vocab ${O}.vocab2  \
		> ${O}.idngram.$i \
		2>${O}.log.idngram.$i

../../CMU-Cam_Toolkit_v2/src/idngram2lm \
	-four_byte_counts \
	-n 2 \
	-vocab_type 0 \
	-vocab ${O}.vocab2 \
	-idngram ${O}.idngram.$i \
	-arpa ${O}.arpa.$i \
	-context ${O}.ccs \
	$BACKOFF \
	2>${O}.log.lm.$i
